name: Daily Backup

on:
  schedule:
    - cron: '0 3 * * *'   # Täglich um 03:00 Uhr UTC
  workflow_dispatch:        # Manueller Start über GitHub-Oberfläche möglich

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  (main)
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependecies
        run: npm install
        working-directory: scripts

      - name: Create backup
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/backup.js

      - name: Push backup to backup repository
        env:
          BACKUP_REPO_TOKEN: ${{ secrets.BACKUP_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${BACKUP_REPO_TOKEN}@github.com/${{ github.repository_owner }}/CfBGtVereinsmeisterschaft-backup.git /tmp/backup-repo

          mkdir -p /tmp/backup-repo/backup
          cp backup/*.json /tmp/backup-repo/backup/

          cd /tmp/backup-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add backup/
          git diff --staged --quiet || git commit -m "Datensicherung $(date +'%Y-%m-%d')"
          git push
